name: Update Leaderboard

on:
  schedule:
    - cron: "0 19 * * 0" # tiap Minggu jam 19:00 (UTC)
  workflow_dispatch:

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install @octokit/rest markdown-table fs

      - name: Run Update Script
        run: node scripts/updateLeaderboard.js

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update leaderboard [skip ci]" || echo "No changes to commit"
          git push
