name: 🚀 Auto Update README

on:
  push:
    branches:
      - main
  workflow_dispatch: # Bisa jalan manual juga

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update README.md
        run: |
          echo "🔥 README terakhir diupdate pada: $(date)" >> README.md

      - name: Commit & Push changes
        run: |
          git add README.md
          git commit -m "chore: auto update README"
          git push
